export const GRID_PIXEL_DIMENSIONS = { WIDTH: 500, HEIGHT: 500 };
export const GRID_SIZE = { ROWS: 8, COLUMNS: 8 };
export const SELECT_GRID_SIZE = {
  ROWS: GRID_SIZE.ROWS - 1,
  COLUMNS: GRID_SIZE.COLUMNS - 1,
};
export const JEWEL_DIAMETER = GRID_PIXEL_DIMENSIONS.HEIGHT / GRID_SIZE.ROWS;
